baseURL = "https://canting2002.github.io/"
languageCode = "en-us"
title = "canting plog"
theme = "ananke"

[[menu.main]]
  identifier = "assignments" 
  name = "Assignment1"      
  url = "/assignments/"
  weight = 3           